_login:
    pattern:  /
    defaults: { _controller: TwitterBundle:Login:index }
 
_activate:
    pattern:  /activate/{activation_hash}
    defaults: { _controller: TwitterBundle:Login:index } 
    
_signup:
    path: /signup
    defaults: { _controller: TwitterBundle:Login:signup }
    
_logout:
    path: /logout
    defaults: { _controller: TwitterBundle:Login:logout }
    
_home:
    path: /home/{show}
    defaults: { _controller: TwitterBundle:Home:home, show:all_tweets }
    requirements:
        show: |all_users|all_tweets|my_tweets|following|followers|search
        
_delete_tweet:
    path: /{show}/{tweet_id}
    defaults: { _controller: TwitterBundle:Home:delete }
    requirements:
        show: all_tweets|my_tweets
        tweet_id: \d+
    
_ajax_follow:
    path: /ajax/follow/{user_id}/{following}
    defaults: { _controller: TwitterBundle:Home:ajaxFollow }
    requirements:
        user_id: \d+
        following: 0|1
    
_ajax_retweet:
    path: /ajax/retweet/{tweet_id}/{retweeted}
    defaults: { _controller: TwitterBundle:Home:ajaxRetweet }
    requirements:
        tweet_id: \d+
        retweeted: 0|1
        
_ajax_tweets:
    path: /ajax/home/{show}/{tweet_id}/{recursive}
    defaults: { _controller: TwitterBundle:Home:ajaxTweets }
    requirements:
        show: all_tweets|my_tweets
        tweet_id: \d+
        recursive: 1|0